"use strict"
var _typeof="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e},BJ_REPORT=function(e){if(e.BJ_REPORT)return e.BJ_REPORT
function s(e,n){return Object.prototype.toString.call(e)==="[object "+(n||"Object")+"]"}function g(e){return"object"===(void 0===e?"undefined":_typeof(e))&&!!e}var d=[],m={uin:0,url:"https://badjs.weixinbridge.com/badjs",combo:0,level:4,ignore:[],random:1,delay:0,submit:null}
function t(n){try{if(n.stack){var e=n.stack.match("https?://[^\n]+"),i=(e=e?e[0]:"").match(":(\\d+):(\\d+)")
i=i||[0,0,0]
var t=c(n).replace(/https?\:\/\/.*?\.js\:/g,"")
return 0==(r=t,o=window.navigator.userAgent,!(-1<r.indexOf("TypeError: #<KeyboardEvent> is not a function")||-1<r.indexOf("TypeError: #<MouseEvent> is not a function")||-1<r.indexOf("ReferenceError: LIST_INFO is not defined")||-1<r.indexOf("TypeError: e is not a constructor")||location&&/token=\d+/.test(location.href)&&"0"==wx.uin||/Mozilla\/5.0.*ipad.*BaiduHD/i.test(o)&&-1<r.indexOf("ReferenceError: Can't find variable: bds")||/Linux; U; Android.*letv/i.test(o)&&-1<r.indexOf("ReferenceError: diableNightMode is not defined")))?null:{msg:t,rowNum:i[1],colNum:i[2],target:e.replace(i[0],"")}}return n}catch(e){return n}var r,o}function u(e,n){var i,t=[],r=[],o=[]
if(g(e))for(var c in e.level=e.level||m.level,e){var a=e[c]
if(null!==(i=a)&&(s(i,"Number")||i)){if(g(a))try{a=JSON.stringify(a)}catch(e){a="[BJ_REPORT detect value stringify error] "+e.toString()}o.push(c+":"+a),t.push(c+"="+encodeURIComponent(a)),r.push(c+"["+n+"]="+encodeURIComponent(a))}}return[r.join("&"),o.join(","),t.join("&")]}function l(e){var n=e.replace(/\&_t=\d*/,"")
for(var i in a)if(a[i]==n)return
if(a.push(n),m.submit)m.submit(e)
else{var t=new Image
o.push(t),t.src=e}var r="error";(r=e.match(/msg=(.*?)&/))&&r[1]&&(r=r[1]),wx&&wx.uin&&(r+=encodeURIComponent("|uin|"+wx.uin)),m.key&&((t=new Image).src="/misc/jslog?id="+m.key+"&content="+r+"&level=error"),(new Image).src="/misc/jslog?id=65&content="+r+"&level=error"}var c=function(e){var n=e.stack.replace(/\n/gi,"").split(/\bat\b/).slice(0,5).join("@").replace(/\?[^:]+/gi,""),i=e.toString()
return n.indexOf(i)<0&&(n=i+"@"+n),n},o=[],a=[],f=[],p=0,r=function(e){if(m.report){for(;d.length;){var n=!1,i=d.shift(),t=u(i,f.length)
if(s(m.ignore,"Array"))for(var r=0,o=m.ignore.length;r<o;r++){var c=m.ignore[r]
if(s(c,"RegExp")&&c.test(t[1])||s(c,"Function")&&c(i,t[1])){n=!0
break}}n||(m.combo?f.push(t[0]):l(m.report+t[2]+"&_t="+ +new Date),m.onReport&&m.onReport(m.id,i))}var a=f.length
if(a){var g=function(){clearTimeout(p),console.log("comboReport"+f.join("&")),l(m.report+f.join("&")+"&count="+a+"&_t="+ +new Date),p=0,f=[]}
e?g():p||(p=setTimeout(g,m.delay,!0),console.log("_config.delay"+m.delay))}}},I={KEY:67,IDS:{DEFAULT:"5",MASS:"6",SELF_MENU:"7",LINK:"11",AUTO_REPLY:"12",COMMENT:"13",VOTE:"14",KF:"15",REWARD:"16",COPYRIGHT:"17",MSG:"18",USER:"19",LIST:"20",AUDIO:"21",VEDIO:"22",APPMSG:"4",AD:"23",ANALYSIS:"24",SETTING:"25",VERIFY:"26",SAFE:"27",ILLEGAL:"28",ADVANCED:"29",REGISTER:"30",TMPL:"31",IE:"32",CARD:"33",SHOP:"34",TMPLMSG:"35",HOME:"36",Android:"37",IOS:"38",IBEACON:"72",MERCHANT:"82"},destory:function(){r=function(){}},push:function(e,n){if(Math.random()>=m.random)return I
var i
if(g(e)){if(i=t(e),n&&(i.msg+="["+n+"]"),i){if(i.target&&0==/^https?\:\/\/(mp\.weixin\.qq\.com|res\.wx\.qq\.com)/.test(i.target))return I
d.push(i)}}else n&&(e+="["+n+"]"),d.push({msg:e})
return r(),I},report:function(e,n){return e&&I.push(e,n),I},info:function(e){return e&&(g(e)?e.level=2:e={msg:e,level:2},I.push(e)),I},debug:function(e){return e&&(g(e)?e.level=1:e={msg:e,level:1},I.push(e)),I},init:function(e){for(var n in e)m[n]=e[n]
var i=parseInt(m.id,10)
n=parseInt(m.key,10)
return window.navigator.userAgent&&/;\s*MSIE\s*[8|7]\.0b?;/i.test(window.navigator.userAgent)?(i=I.IDS.IE,n=0):-1<window.navigator.userAgent.indexOf("Android")||-1<window.navigator.userAgent.indexOf("Adr")?(i=I.IDS.Android,n=0):window.navigator.userAgent.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/)&&(i=I.IDS.IOS,n=0),i&&n&&(m.report=m.url+"?id="+i+"&key="+n+"&uin="+(wx&&wx.uin)+"&from="+encodeURIComponent(location.href)+"&"),I},monitor:function(e,n,i){n=n||"badjs|monitor",e&&((new Image).src="/misc/jslog?id="+e+"&content="+encodeURIComponent(n)+"&level=error")
i&&((new Image).src=m.url+"?id="+i+"&msg="+encodeURIComponent(n)+"&uin="+(wx&&wx.uin)+"&from="+encodeURIComponent(location.href)+"&level=4")},getConfig:function(){return m}}
return"undefined"!=typeof console&&console.error&&setTimeout(function(){var e=((location.hash||"").match(/([#&])BJ_ERROR=([^&$]+)/)||[])[2]
e&&console.error("BJ_ERROR",decodeURIComponent(e).replace(/(:\d+:\d+)\s*/g,"$1\n"))},0,!0),m.id=I.IDS.DEFAULT,m.key=I.KEY,function(){if(m.id!=I.IDS.DEFAULT||m.key!=I.KEY)return m.id,m.key
var e={_href:location.href,href:location.href.replace("https://mp.weixin.qq.com/","")};-1<e.href.indexOf("?")?e.cgi=e.href.match(/.*?\?/g)[0].slice(0,-1):e.cgi=e.href
var n=(e.href+"&").match(/action\=(.*?)&/)
n&&n[1]&&(e.action=n[1])
var i=I.IDS.DEFAULT,t=I.KEY
"cgi-bin/masssendpage"==e.cgi?(i=I.IDS.MASS,t=66):"advanced/autoreply"==e.cgi?(i=I.IDS.AUTO_REPLY,t=70):"advanced/selfmenu"==e.cgi?(i=I.IDS.SELF_MENU,t=68):"misc/appmsgcomment"==e.cgi?(i=I.IDS.COMMENT,t=71):"cgi-bin/newoperatevote"==e.cgi?(i=I.IDS.VOTE,t=72):"misc/kf"==e.cgi?(i=I.IDS.KF,t=73):"merchant/rewardstat"==e.cgi||"merchant/reward"==e.cgi?(i=I.IDS.REWARD,t=74):"cgi-bin/appmsgcopyright"==e.cgi||"cgi-bin/imgcopyright"==e.cgi||"cgi-bin/ori_video"==e.cgi?(i=I.IDS.COPYRIGHT,t=75):"cgi-bin/message"==e.cgi?(i=I.IDS.MSG,t=76):"cgi-bin/user_tag"==e.cgi?(i=I.IDS.USER,t=77):"cgi-bin/appmsg"==e.cgi&&("list_card"==e.action||"list"==e.action)||"cgi-bin/filepage"==e.cgi?(i=I.IDS.LIST,t=78):"cgi-bin/operate_voice"==e.cgi?(i=I.IDS.AUDIO,t=79):"cgi-bin/appmsg"==e.cgi&&"video_edit"==e.action?(i=I.IDS.VEDIO,t=80):"cgi-bin/appmsg"==e.cgi&&"edit"==e.action?(i=I.IDS.APPMSG,t=62):"cgi-bin/frame"==e.cgi&&/t=ad_system/.test(e.href)||/merchant\/ad_/.test(e.cgi)?(i=I.IDS.AD,t=81):"misc/useranalysis"==e.cgi||"misc/appmsganalysis"==e.cgi||"misc/menuanalysis"==e.cgi||"misc/messageanalysis"==e.cgi||"misc/interfaceanalysis"==e.cgi?(i=I.IDS.ANALYSIS,t=82):"cgi-bin/settingpage"==e.cgi||"acct/contractorinfo"==e.cgi?(i=I.IDS.SETTING,t=83):"merchant/store"==e.cgi||"merchant/order"==e.cgi||"acct/wxverify"==e.cgi?(i=I.IDS.VERIFY,t=84):"cgi-bin/safecenterstatus"==e.cgi?(i=I.IDS.SAFE,t=85):"cgi-bin/illegalrecord"==e.cgi?(i=I.IDS.ILLEGAL,t=86):"advanced/advanced"==e.cgi||"advanced/diagram"==e.cgi||"cgi-bin/frame"==e.cgi&&/t=advanced\/dev_tools_frame/.test(e.href)?(i=I.IDS.ADVANCED,t=87):"acct/contractorpage"==e.cgi?(i=I.IDS.REGISTER,t=88):"cgi-bin/readtemplate"==e.cgi?(i=I.IDS.TMPL,t=89):"advanced/tmplmsg"==e.cgi?(i=I.IDS.TMPLMSG,t=90):"merchant/entityshop"==e.cgi||"merchant/newentityshop"==e.cgi?(i=I.IDS.SHOP,t=92):"merchant/goods"==e.cgi||"merchant/goodsgroup"==e.cgi||"merchant/shelf"==e.cgi||"merchant/goodsimage"==e.cgi||"merchant/delivery"==e.cgi||"merchant/productorder"==e.cgi||"merchant/merchantstat"==e.cgi||"merchant/introduction"==e.cgi||"merchant/merchantpush"==e.cgi||"merchant/merchantentrance"==e.cgi?(i=I.IDS.MERCHANT,t=104):"cgi-bin/home"==e.cgi?(i=I.IDS.HOME,t=93):"merchant/cardapply"==e.cgi&&"listapply"==e.action?t=95:-1<e.cgi.indexOf("beacon")&&(i=I.IDS.IBEACON,t=96),m.id=i,m.key=t,wx&&"en_US"==wx.lang&&(t=i=125)}(),I.init(),I}(window)
