define("pages/modules/media_dialog/video_snap_dialog/time_format.js",[],function(e,t,n){"use strict"
function g(e){var t=e+""
return 2<=t.length?t:"0"+t}n.exports={getFullTime:function(e){var t=new Date(1e3*e)
return t.getFullYear()<=(new Date).getFullYear()?g(t.getMonth()+1)+"月"+g(t.getDate())+"日 "+g(t.getHours())+":"+g(t.getMinutes()):t.getFullYear()+"年"+g(t.getMonth()+1)+"月"+g(t.getDate())+"日 "+g(t.getHours())+":"+g(t.getMinutes())}}})
define("pages/modules/media_dialog/insert_profile_dialog/insertProfileDialog4Web1.js",["pages/modules/media_dialog/insert_profile_dialog/insert_profile_dialog.js"],function(e,i,o){"use strict"
function n(){return{defaultShow:!1,isShow:!1,insertedNum:0}}o.exports={getParams:n,bindEvent:function(i){i.eventBus.$on("requireInsertProfileDialog",function(){i.isRequired||(e("pages/modules/media_dialog/insert_profile_dialog/insert_profile_dialog.js"),i.isRequired=!0)}),i.eventBus.$on("showInsertProfileDialog",function(){var e=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{}
i.eventBus.$emit("requireInsertProfileDialog"),function(e,i){var o=n()
for(var r in i)void 0!==o[r]&&(o[r]=i[r])
for(var a in o)Object.prototype.hasOwnProperty.call(o,a)&&(e.params[a]=o[a])
e.params.isShow=!0,e.params.defaultShow=!0}(i,e),i.eventBus.$emit("update-component",{key:"mp-insert-profile-dialog",params:i.params})})},close:function(e){e.eventBus.$emit("showInsertProfileDialog_callback",e.data)}}})
define("pages/modules/media_dialog/insert_profile_dialog/insert_profile_dialog.js",["pages/modules/media_dialog/insert_profile_dialog/insert_profile_dialog.tpl.js","pages/modules/utils/cgi.js","vue-weui/src/dialog/dialog.js","pages/modules/media_dialog/insert_profile_dialog/insert_profile_dialog.css.js","pages/modules/media/profile_dialog_item/profile_dialog_item.js"],function(e,t,i){"use strict"
function n(e){return function(){var a=e.apply(this,arguments)
return new Promise(function(o,r){return function t(e,i){try{var s=a[e](i),n=s.value}catch(e){return void r(e)}if(!s.done)return Promise.resolve(n).then(function(e){t("next",e)},function(e){t("throw",e)})
o(n)}("next")})}}var s=e("pages/modules/media_dialog/insert_profile_dialog/insert_profile_dialog.tpl.js"),o=e("pages/modules/utils/cgi.js")
e("vue-weui/src/dialog/dialog.js"),e("pages/modules/media_dialog/insert_profile_dialog/insert_profile_dialog.css.js"),e("pages/modules/media/profile_dialog_item/profile_dialog_item.js"),Vue.component("mp-insert-profile-dialog",{template:s,data:function(){return{dialogShow:!0,recentlyLoading:!1,userStartPosition:0,loading:!1,recentlyUseList:[],isInitial:!0,inputValue:"",loadMoreCountSearchValue:"",showRecentUser:!0,hasSearch:!1,userList:[],searchResult:"",loadMoreAccount:!1,noMoreAccount:!1,loadingAccount:!1,selectedUser:null}},mounted:function(){!0===this.value&&this.show(),this.getRecentlyUseList(),document.getElementsByClassName("profile_search_mod")[0].addEventListener("scroll",this.throttling(50,this.loadMoreFunction))},watch:{dialogShow:function(e){this.$emit("input",e)},value:function(e){!0===e?this.show():this.hide()}},computed:{submitBtnDisabled:function(){return null===this.selectedUser||void 0===this.selectedUser}},methods:{show:function(){!1===this.dialogShow&&(this.dialogShow=!0)},hide:function(){!0===this.dialogShow&&(this.dialogShow=!1)},dialogClose:function(){this.hide(),this.$emit("cancel"),this.recentlyLoading=!1,this.userStartPosition=0,this.loading=!1,this.recentlyUseList=[],this.isInitial=!0,this.inputValue="",this.loadMoreCountSearchValue="",this.showRecentUser=!0,this.hasSearch=!1,this.userList=[],this.searchResult="",this.loadMoreAccount=!1,this.noMoreAccount=!1,this.loadingAccount=!1,this.selectedUser=null},loadMoreFunction:function(i){var s=this
return n(regeneratorRuntime.mark(function e(){var t
return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:if(!((t=i.srcElement?i.srcElement:i.target).scrollHeight-t.scrollTop-t.clientHeight<35)){e.next=17
break}if(!s.hasSearch){e.next=17
break}if(s.loadMoreAccount||s.noMoreAccount)return e.abrupt("return")
e.next=5
break
case 5:return s.loadMoreAccount=!0,e.prev=6,e.next=9,s.searchAccountList(s.loadMoreCountSearchValue,s.userStartPosition)
case 9:0===e.sent.list.length&&(s.noMoreAccount=!0),e.next=16
break
case 13:e.prev=13,e.t0=e.catch(6),console.log(e.t0)
case 16:s.loadMoreAccount=!1
case 17:case"end":return e.stop()}},e,s,[[6,13]])}))()},throttling:function(e,t){var i=0<arguments.length&&void 0!==e?e:500,s=t,n=+new Date
return function(e){var t=+new Date
e.preventDefault(),i<=t-n&&(s(e),n=t)}},dialogVisibleChange:function(e){e?document.getElementsByTagName("body")[0].setAttribute("style","height:100%;overflow: hidden !important"):document.getElementsByTagName("body")[0].setAttribute("style","overflow: visible")},getRecentlyUseList:function(){var t=this
this.recentlyLoading=!0,o.get({url:"/cgi-bin/operate_appmsg?sub=get_used_biz_card"},function(e){e&&e.base_resp&&0===e.base_resp.ret&&(t.recentlyUseList=e.list),t.recentlyLoading=!1})},searchAccountList:function(e,s){var n=this
return new Promise(function(t,i){n.loadingAccount||(n.loadingAccount=!0,o.get({url:"/cgi-bin/searchbiz?action=search_biz",data:{scene:1,begin:s,count:10,query:e}},function(e){e&&e.base_resp&&0===e.base_resp.ret?(n.userList=n.userList.concat(e.list),n.userStartPosition+=10,t(e)):i(e),n.loadingAccount=!1}))})},jumpRecently:function(e){this.isInitial=!1,this.hasSearch=!0,this.showRecentUser=!0,this.inputValue=e.nickname,this.search()},search:function(){var t=this
""!==this.inputValue&&(this.loading=!0,this.isInitial=!1,this.hasSearch=!0,this.userList=[],this.noMoreAccount=!1,this.userStartPosition=0,this.selectedUser=null,this.searchResult="",this.loadMoreAccount=!1,this.loadMoreCountSearchValue=this.inputValue,this.searchAccountList(this.loadMoreCountSearchValue,this.userStartPosition).then(function(e){t.loading=!1,e.list&&0!==e.list.length||(t.searchResult="暂无搜索结果")}).catch(function(){t.loading=!1,t.searchResult="系统繁忙"}))},selectedStatusChange:function(e){if(null!==this.selectedUser)if(e.fakeid===this.selectedUser.fakeid)this.selectedUser=null
else{var t=this.selectedUser.fakeid
this.$refs[t][0].changeStatus(),this.selectedUser=e}else this.selectedUser=e},insertRecentUse:function(e){o.get({url:"/cgi-bin/searchbiz?action=add_used_biz_card",data:{fakeid:e.fakeid}})},submit:function(){var e=[this.selectedUser]
this.insertRecentUse(this.selectedUser),this.$emit("insert",e),this.hide()}}})})
define("pages/modules/media_dialog/insert_profile_dialog/insert_profile_dialog.tpl.js",[],function(i,e,s){return'<mp-dialog :width="960" weui="true" v-model="dialogShow" title="插入公众号" wrap-class="profile_dialog" @close="dialogClose" @visible-change="dialogVisibleChange" rootElm="#vue_app">  <div ref="mainView" :class="{    \'profile_search_mod\': true,     \'profile_search_status_initial\': isInitial }" :style=" isInitial ? \'\' : \'height: 564px; overflow-y: scroll;\'" >    <template v-if="true">      <mp-search v-if="true" placeholder="请输入公众号名称或公众号微信号" v-model="inputValue" @search="search"></mp-search>      <div class="profile_history_mod_wrp" v-if="showRecentUser">        <i v-if="recentlyLoading" class="weui-desktop-loading"></i>        <div class="profile_history_mod" v-if="showRecentUser && recentlyUseList.length && !recentlyLoading">          <strong class="profile_history_label">最近使用</strong>          <ul class="profile_history_list">            <li class="profile_history_item" v-for="(item, index) in recentlyUseList" @click="jumpRecently(item)">{{item.nickname}}</li>          </ul>        </div>      </div>      <div class="profile_search_result_mod" v-if="hasSearch">        <div class="profile_search_card_area">          <div class="profile_search_card_list weui-desktop-grid" v-if="userList.length">            <template v-for="(item, index) in userList">              <div :class="{                \'weui-desktop-grid__col\': true,                \'profie_single_column\': userList.length === 1              }">                <mp-profile-dialog-item                 :item="item"                :inputValue="inputValue"                :ref="item.fakeid"                @click.native="selectedStatusChange(item)"> </mp-profile-dialog-item>              </div>            </template>          </div>                    <div class="weui-desktop-loadmore" v-if="loadMoreAccount"><i class="weui-desktop-loading"></i></div>          <div class="weui-desktop-loadmore weui-desktop-loadmore_end" v-if="noMoreAccount">暂无更多公众号</div>        </div>                <div v-if="loading" class="weui-desktop-empty-tips"><i class="weui-desktop-loading"></i></div>        <div v-if="searchResult" class="weui-desktop-empty-tips">{{searchResult}}</div>      </div>          </template>      </div>    <template slot="footer" v-if="!isInitial">      <mp-button v-if="!isInitial" :class="{\'profile_submit_btn_disabled\': submitBtnDisabled}" :disabled="submitBtnDisabled" type="primary" @click="submit">插入</mp-button>    </template></mp-dialog>'})
define("pages/modules/media_dialog/insert_profile_dialog/insert_profile_dialog.css.js", [], function (require, exports, module){module.exports = "@grid BreakPoints: {  xs: 0;  sm: 576px;  md: 768px;  lg: 992px;  xl: 1200px;}@container MaxWidths: {  xs: auto;  sm: 540px;  md: 720px;  lg: 960px;  xl: 1140px;}/*How to usefont-family: 'wechatnum';*/.weui-desktop-grid {  display: -ms-flexbox;  display: flex;  -ms-flex-wrap: wrap;      flex-wrap: wrap;  margin-left: -4px;  margin-right: -4px;}.weui-desktop-grid__col {  padding: 0 4px;  box-sizing: border-box;  min-width: 0;}.profile_dialog .weui-desktop-dialog {  position: relative;}.profile_dialog em.highlight {  font-style: normal;}.profile_dialog .weui-desktop-dialog__hd {  height: 88px;}.profile_dialog .weui-desktop-dialog__title {  margin: 10px auto;}.profile_search_mod {  padding: 0 32px;}.profile_search_mod .weui-desktop-search {  width: 300px;  margin: 0 auto;}.profile_search_mod .profile_selected_tips {  position: absolute;  left: 40px;  bottom: 26px;  max-width: 320px;}.profile_search_mod .weui-desktop-loadmore {  margin: 20px auto;}.profile_search_status_initial {  padding-top: 125px;  padding-bottom: 240px;}.profile_search_result_mod {  margin-top: 24px;}.profile_search_card_area {  padding: 0 80px;}.profile_search_card_list .weui-desktop-grid__col {  -ms-flex: 0 0 50%;      flex: 0 0 50%;}.profile_search_card_list .weui-desktop-grid__col {  -ms-flex: 0 0 50%;      flex: 0 0 50%;}.profile_selected_tips {  position: absolute;  bottom: 34px;  cursor: pointer;}.profile_selected_tips a {  margin-left: 10px;}.profile_search_card_list .weui-desktop-grid__col {  padding: 0 8px;}.profie_single_column {  margin: 0 auto;}.profile_history_mod_wrp {  margin: 20px auto 0;  text-align: center;  max-width: 64%;}.profile_history_list {  display: inline;}.profile_history_label,.profile_history_item {  display: inline-block;  vertical-align: top;  margin: 0 10px;}.profile_history_label {  font-weight: 400;}.profile_history_item {  cursor: pointer;  color: var(--weuiDesktop_FG_Text_linkColor);}";});define("pages/modules/media/profile_dialog_item/profile_dialog_item.js",["pages/modules/media/profile_dialog_item/profile_dialog_item.tpl.js","pages/modules/media/profile_dialog_item/profile_dialog_item.css.js"],function(e,i,t){"use strict"
var a=e("pages/modules/media/profile_dialog_item/profile_dialog_item.tpl.js")
e("pages/modules/media/profile_dialog_item/profile_dialog_item.css.js"),Vue.component("mp-profile-dialog-item",{template:a,props:{item:{type:Object},fakeID:{},inputValue:{type:String}},mounted:function(){var e=this.nickname?this.nickname:this.alias,i=""
if(-1===e.toLowerCase().indexOf(this.inputValue)&&-1===e.toUpperCase().indexOf(this.inputValue))for(var t=0;t<e.length;t++)-1!==this.inputValue.indexOf(e[t].toLowerCase())||-1!==this.inputValue.indexOf(e[t].toUpperCase())?i+='<em class="highlight">'+e[t]+"</em>":i+=e[t]
else i=e.replace(new RegExp(""+this.inputValue,"gi"),'<em class="highlight">'+this.inputValue+"</em>")
this.highLightName=i},data:function(){return{cardSelected:!1,round_head_img:this.item.round_head_img,nickname:this.item.nickname,alias:this.item.alias,signature:this.item.signature,highLightName:""}},computed:{},methods:{changeCardStatus:function(){this.cardSelected=!this.cardSelected,this.$emit("selectedStatusChange",this.item)},changeStatus:function(){this.cardSelected=!this.cardSelected}}})})
define("pages/modules/media/profile_dialog_item/profile_dialog_item.tpl.js",[],function(e,i,a){return'<div :class="{\'appmsg_card_context wx_profile_card\': true,              wx_profile_card_selected: cardSelected}" @click="changeCardStatus">  <div class="wx_profile_card_bd">    <div class="wx_profile  weui-flex">      <div class="wx_profile_hd">        <template v-if="round_head_img">          <img class="wx_profile_avatar" :src="round_head_img" :alt="nickname">        </template>        <template v-else>          <img class="wx_profile_avatar" src="http://mmbiz.qpic.cn/mmbiz/a5icZrUmbV8p5jb6RZ8aYfjfS2AVle8URwBt8QIu6XbGewB9wiaWYWkPwq4R7pfdsFibuLkic16UcxDSNYtB8HnC1Q/0" :alt="nickname">        </template>      </div>      <div class="wx_profile_bd weui-flex__item">        <strong class="wx_profile_nickname">            <span v-if="nickname" v-html="highLightName">            </span>            <span v-else v-html="highLightName">            </span>        </strong>        <div class="wx_profile_desc">{{signature}}</div>      </div>    </div>  </div></div>'})
define("pages/modules/media/profile_dialog_item/profile_dialog_item.css.js", [], function (require, exports, module){module.exports = "@grid BreakPoints: {  xs: 0;  sm: 576px;  md: 768px;  lg: 992px;  xl: 1200px;}@container MaxWidths: {  xs: auto;  sm: 540px;  md: 720px;  lg: 960px;  xl: 1140px;}/*How to usefont-family: 'wechatnum';*/.highlight {  color: #07C160;}.wx_profile_card {  margin: 16px 0 0;  width: 100%;  line-height: 1.4;  border: 1px solid transparent;}.wx_profile_card:hover {  border: 1px solid rgba(7, 193, 96, 0.3);}.wx_profile_card.wx_profile_card_selected {  background: rgba(7, 193, 96, 0.1);  border-radius: 4px;  border: 1px solid #07C160;}.wx_profile {  -ms-flex-align: center;      align-items: center;  display: -ms-flexbox;  display: flex;  padding: 20px 16px;}.wx_profile_hd {  display: -ms-flexbox;  display: flex;  padding-right: 10px;}.wx_profile_avatar {  width: 44px;  height: 44px;  border-radius: 100%;}.wx_profile_nickname {  overflow: hidden;  text-overflow: ellipsis;  white-space: nowrap;  width: 100%;  color: rgba(0, 0, 0, 0.9);  font-size: 14px;  display: block;  float: left;  font-weight: 500;}.wx_profile_desc {  color: rgba(0, 0, 0, 0.5);  font-size: 14px;  overflow: hidden;  text-overflow: ellipsis;  white-space: nowrap;  margin-top: 4px;}.wx_profile_tips_meta:before {  content: \"\\00B7\";  margin-left: 5px;  margin-right: 5px;}.wx_profile_tips_meta:first-child:before,.wx_profile_tips_meta:empty:before {  display: none;}.weui-flex__item {  display: -ms-flexbox;  display: flex;  -ms-flex: 1;      flex: 1;  min-width: 0;  -ms-flex-wrap: wrap;      flex-wrap: wrap;}.weui-flex__item .meta_primary:last-child {  margin-right: 0;}.appmsg_card_context {  position: relative;  background-color: #F7F7F7;  border-radius: 8px;  -webkit-user-select: none;      -ms-user-select: none;          user-select: none;}";});define("pages/modules/media_dialog/sub_notify_dialog/subNotifyDialog4Web1.js",["pages/modules/media_dialog/sub_notify_dialog/sub_notify_dialog.js"],function(e,i,o){"use strict"
function s(){return{defaultShow:!1,isShow:!1,insertedNum:0}}o.exports={getParams:s,bindEvent:function(i){i.eventBus.$on("requireInsertSubNotifyDialog",function(){i.isRequired||(e("pages/modules/media_dialog/sub_notify_dialog/sub_notify_dialog.js"),i.isRequired=!0)}),i.eventBus.$on("showInsertSubNotifyDialog",function(){var e=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{}
i.eventBus.$emit("requireInsertSubNotifyDialog"),function(e,i){var o=s()
for(var t in i)void 0!==o[t]&&(o[t]=i[t])
for(var a in o)Object.prototype.hasOwnProperty.call(o,a)&&(e.params[a]=o[a])
e.params.isShow=!0,e.params.defaultShow=!0}(i,e),i.eventBus.$emit("update-component",{key:"mp-sub-notify-dialog",params:i.params})})},close:function(e){e.eventBus.$emit("showInsertSubNotifyDialog_callback",e.data)}}})
define("pages/modules/media_dialog/sub_notify_dialog/sub_notify_dialog.js",["pages/modules/media_dialog/sub_notify_dialog/sub_notify_dialog.css.js","vue-weui/src/dialog/dialog.js","vue-weui/src/pagination/pagination.js","vue-weui/src/search/search.js","vue-weui/src/form/form.js","vue-weui/src/form/form_item.js","vue-weui/src/input/input.js","pages/modules/media_dialog/sub_notify_dialog/sub_notify_dialog.tpl.js","pages/modules/utils/cgi.js"],function(t,e,i){"use strict"
var s=Object.assign||function(t){for(var e=1;e<arguments.length;e++){var i=arguments[e]
for(var s in i)Object.prototype.hasOwnProperty.call(i,s)&&(t[s]=i[s])}return t}
t("pages/modules/media_dialog/sub_notify_dialog/sub_notify_dialog.css.js"),t("vue-weui/src/dialog/dialog.js"),t("vue-weui/src/pagination/pagination.js"),t("vue-weui/src/search/search.js"),t("vue-weui/src/form/form.js"),t("vue-weui/src/form/form_item.js"),t("vue-weui/src/input/input.js")
var o=t("pages/modules/media_dialog/sub_notify_dialog/sub_notify_dialog.tpl.js"),n=t("pages/modules/utils/cgi.js")
Vue.component("mp-sub-notify-dialog",{template:o,props:{value:{type:Boolean,default:!1},insertedNum:{type:Number,default:0}},data:function(){return{loading:!0,dialogShow:!1,isInitial:!0,tmplList:[],currentPage:1,perPage:5,maxSelectedCount:5}},mounted:function(){this.getTemplates(),!0===this.value&&this.show()},computed:{selectedList:function(){return this.tmplList.filter(function(t){return t.isChecked})},selectedCount:function(){return this.selectedList.length},totalCount:function(){return this.tmplList.length},filteredList:function(){var t=this,e=(this.currentPage-1)*this.perPage,i=this.selectedList.some(function(t){return 2===t.type}),s=this.selectedList.some(function(t){return 2!==t.type}),o=this.tmplList.slice(e,e+this.perPage)
return o.forEach(function(e){!e.isChecked&&(t.selectedCount>=t.maxSelectedCount||i&&2!==e.type||s&&2===e.type||t.selectedList.some(function(t){return t.title===e.title}))?e.isDisabled=!0:e.isDisabled=!1}),o}},watch:{dialogShow:function(t){this.$emit("input",t)},value:function(t){!0===t?this.show():this.hide()}},methods:{show:function(){!1===this.dialogShow&&(this.dialogShow=!0)},hide:function(){!0===this.dialogShow&&(this.dialogShow=!1)},dialogClose:function(){this.hide(),this.$emit("cancel")},dialogVisibleChange:function(t){t?document.getElementsByTagName("body")[0].setAttribute("style","height:100%;overflow: hidden !important"):document.getElementsByTagName("body")[0].setAttribute("style","overflow: visible")},submit:function(){this.$emit("insert",{templateidlist:this.selectedList.map(function(t){return t.priTmplId}).join(",")}),this.hide()},getTemplates:function(){var e=this
this.loading=!0,n.get({url:"/wxamp/cgi/newtmpl/get_pritmpllist",data:{random:Math.random()}},function(t){e.loading=!1,0===t.ret&&(e.tmplList=t.list.map(function(t){return s({},t,{isChecked:!1,isDisabled:!1})}))})},pageChange:function(t){var e=t.currentPage
0<e&&(this.currentPage=e)}}})})
